"""empty message

Revision ID: 11669922604f
Revises: 6443fdc07128
Create Date: 2024-07-09 15:48:22.814749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11669922604f'
down_revision = '6443fdc07128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoppingcart', schema=None) as batch_op:
        batch_op.drop_column('product_price_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoppingcart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_price_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'product_prices', ['product_price_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
