"""empty message

Revision ID: 586dfdece8c7
Revises: 6cec1638154d
Create Date: 2024-07-09 16:07:09.361618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '586dfdece8c7'
down_revision = '6cec1638154d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoppingcart', schema=None) as batch_op:
        batch_op.drop_column('product_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoppingcart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_price', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
