"""add user_ip to user connection table

Revision ID: 803028952ef2
Revises: ad2a4617a11c
Create Date: 2024-08-12 17:03:55.250197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803028952ef2'
down_revision = 'ad2a4617a11c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_connection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_ip', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_connection', schema=None) as batch_op:
        batch_op.drop_column('user_ip')

    # ### end Alembic commands ###
