"""empty message

Revision ID: 81426a7caab7
Revises: a4faba39778c
Create Date: 2024-08-24 12:39:58.389747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81426a7caab7'
down_revision = 'a4faba39778c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_history', schema=None) as batch_op:
        batch_op.drop_constraint('barcode', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_history', schema=None) as batch_op:
        batch_op.create_unique_constraint('barcode', ['barcode'])

    # ### end Alembic commands ###
