"""empty message

Revision ID: b2ad31fbbf8a
Revises: 6370e077eca1
Create Date: 2024-08-25 00:32:16.303397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2ad31fbbf8a'
down_revision = '6370e077eca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_products')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('barcode',
               existing_type=sa.TEXT(),
               type_=sa.String(length=250),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               nullable=False)
        batch_op.alter_column('brand',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_index('ix_products_id')
        batch_op.create_unique_constraint('barcode', ['barcode'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_products_id', ['id'], unique=False)
        batch_op.alter_column('brand',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('barcode',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)

    op.create_table('_alembic_tmp_products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('barcode', sa.VARCHAR(length=250), nullable=False),
    sa.Column('name', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('brand', sa.VARCHAR(), nullable=True),
    sa.UniqueConstraint('barcode', name='barcode')
    )
    # ### end Alembic commands ###
