"""empty message

Revision ID: bf0ab781a422
Revises: 1bce75dbceb4
Create Date: 2024-07-17 13:57:09.470723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0ab781a422'
down_revision = '1bce75dbceb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('internal_code_product', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_prices', schema=None) as batch_op:
        batch_op.drop_column('internal_code_product')

    # ### end Alembic commands ###
